services:
  postgres:
    image: postgres:17
    container_name: wirtual-wallet-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: wirtual-wallet

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: